version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: ./app
    ports:
      - "5000:5000"
  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
    depends_on:
      - app